# coding = 'utf-8'

from typing import Any
from method.System.guiddef import *
from method.System.wtypesbase import *
from method.System.unknwnbase import *
from method.System.winusutypes import *
from method.System.unknwnbase import _In_, _Out_, COMFUNCTYPE

OLESTR = LPCWSTR
OLECHAR = WCHAR
POLECHAR = POINTER(OLECHAR)
CIMTYPE = LONG
BSTR = POLECHAR
DATE = DOUBLE
VARIANT_BOOL = SHORT

class tagCY(Structure):
    class DUMMYSTRUCTNAME(Structure):
        _fields_ = [('Hi', LONG)]
    
    _anonymous_ = ['DUMMYSTRUCTNAME']
    _fields_ = [('int64', LONGLONG),
                ('DUMMYSTRUCTNAME', DUMMYSTRUCTNAME)
    ]

CY = tagCY
LPCY = POINTER(CY)
VARTYPE = c_ushort

COINIT_APARTMENTTHREADED = 0x2
COINIT_MULTITHREADED = 0x0

##########################################################################

class SOLE_AUTHENTICATION_SERVICE(Structure):
    _fields_ = [
        ('dwAuthnSvc', DWORD),
        ('dwAuthzSvc', DWORD),
        ('pPrincipalName', OLESTR),
        ('hr', HRESULT)
    ]

class SECURITY_DESCRIPTOR(Structure):
    _fields_ = [
        ('Revision', c_byte),
        ('Sbz1', c_byte),
        ('Control', c_uint16),
        ('Owner', c_void_p),
        ('Group', c_void_p),
        ('Sacl', c_void_p),
        ('Dacl', c_void_p),
    ]


class SAFEARRAYBOUND(Structure):
    _fields_ = [
        ('cElements', ULONG),
        ('lLbound', LONG)
    ]


class SAFEARRAY(Structure):
    _fields_ = [
        ('cDims', USHORT),
        ('fFeatures', USHORT),
        ('cbElements', ULONG),
        ('cLocks', ULONG),
        ('pvData', LPVOID),
        ('rgsabound', POINTER(SAFEARRAYBOUND))
    ]


class DECIMAL_DUMMYSTRUCTNAME(Structure):
    _fields_ = [('scale', BYTE),
                ('sign', BYTE)]


class DECIMAL_DUMMYSTRUCTNAME2(Structure):
    _fields_ = [('Lo32', ULONG),
                ('Mid32', ULONG)]


class DECIMAL_DUMMYUNIONNAME(Union):
    _fields_ = [('DUMMYSTRUCTNAME', DECIMAL_DUMMYSTRUCTNAME),
                ('signscale', USHORT)]


class DECIMAL_DUMMYUNIONNAME2(Union):
    _fields_ = [('DUMMYSTRUCTNAME2', DECIMAL_DUMMYSTRUCTNAME2),
                ('Lo64', c_ulonglong)]


class DECIMAL(Structure):
    _fields_ = [('DUMMYUNIONNAME', DECIMAL_DUMMYUNIONNAME),
                ('Hi32', ULONG),
                ('DUMMYUNIONNAME2', DECIMAL_DUMMYUNIONNAME2)]


class VARIANT__tagBRECORD(Structure):
    _fields_ = [("pvRecord", LPVOID),
                ("pRecInfo", LPVOID)]  # IRecordInfo * pRecInfo;

##############################################
# wbemcli.h
 
LIBID_WbemClient_v1 = DEFINE_GUID(0x7ec196fe, 0x7005, 0x11d1, 0xad,0x90, 0x00,0xc0,0x4f,0xd8,0xfd,0xff)

WBEM_GENUS_CLASS = 1
WBEM_GENUS_INSTANCE = 2

class tag_WBEM_GENUS_TYPE(enum.Enum):
    WBEM_GENUS_CLASS = 1
    WBEM_GENUS_INSTANCE = 2

WBEM_FLAG_CREATE_OR_UPDATE = 0
WBEM_FLAG_UPDATE_ONLY = 0x1
WBEM_FLAG_CREATE_ONLY = 0x2
WBEM_FLAG_UPDATE_COMPATIBLE = 0x0
WBEM_FLAG_UPDATE_SAFE_MODE = 0x20
WBEM_FLAG_UPDATE_FORCE_MODE = 0x40
WBEM_MASK_UPDATE_MODE = 0x60
WBEM_FLAG_ADVISORY = 0x10000

class tag_WBEM_CHANGE_FLAG_TYPE(enum.Enum):
    WBEM_FLAG_CREATE_OR_UPDATE = 0
    WBEM_FLAG_UPDATE_ONLY = 0x1
    WBEM_FLAG_CREATE_ONLY = 0x2
    WBEM_FLAG_UPDATE_COMPATIBLE = 0x0
    WBEM_FLAG_UPDATE_SAFE_MODE = 0x20
    WBEM_FLAG_UPDATE_FORCE_MODE = 0x40
    WBEM_MASK_UPDATE_MODE = 0x60
    WBEM_FLAG_ADVISORY = 0x10000

WBEM_FLAG_RETURN_IMMEDIATELY = 0x10
WBEM_FLAG_RETURN_WBEM_COMPLETE = 0
WBEM_FLAG_BIDIRECTIONAL = 0
WBEM_FLAG_FORWARD_ONLY = 0x20
WBEM_FLAG_NO_ERROR_OBJECT = 0x40
WBEM_FLAG_RETURN_ERROR_OBJECT = 0
WBEM_FLAG_SEND_STATUS = 0x80
WBEM_FLAG_DONT_SEND_STATUS = 0
WBEM_FLAG_ENSURE_LOCATABLE = 0x100
WBEM_FLAG_DIRECT_READ = 0x200
WBEM_FLAG_SEND_ONLY_SELECTED = 0
WBEM_RETURN_WHEN_COMPLETE = 0
WBEM_RETURN_IMMEDIATELY = 0x10
WBEM_MASK_RESERVED_FLAGS = 0x1f000
WBEM_FLAG_USE_AMENDED_QUALIFIERS = 0x20000
WBEM_FLAG_STRONG_VALIDATION = 0x100000

class tag_WBEM_GENERIC_FLAG_TYPE(enum.Enum):
    WBEM_FLAG_RETURN_IMMEDIATELY = 0x10
    WBEM_FLAG_RETURN_WBEM_COMPLETE = 0
    WBEM_FLAG_BIDIRECTIONAL = 0
    WBEM_FLAG_FORWARD_ONLY = 0x20
    WBEM_FLAG_NO_ERROR_OBJECT = 0x40
    WBEM_FLAG_RETURN_ERROR_OBJECT = 0
    WBEM_FLAG_SEND_STATUS = 0x80
    WBEM_FLAG_DONT_SEND_STATUS = 0
    WBEM_FLAG_ENSURE_LOCATABLE = 0x100
    WBEM_FLAG_DIRECT_READ = 0x200
    WBEM_FLAG_SEND_ONLY_SELECTED = 0
    WBEM_RETURN_WHEN_COMPLETE = 0
    WBEM_RETURN_IMMEDIATELY = 0x10
    WBEM_MASK_RESERVED_FLAGS = 0x1f000
    WBEM_FLAG_USE_AMENDED_QUALIFIERS = 0x20000
    WBEM_FLAG_STRONG_VALIDATION = 0x100000

WBEM_STATUS_COMPLETE = 0
WBEM_STATUS_REQUIREMENTS = 1
WBEM_STATUS_PROGRESS = 2
WBEM_STATUS_LOGGING_INFORMATION = 0x100
WBEM_STATUS_LOGGING_INFORMATION_PROVIDER = 0x200
WBEM_STATUS_LOGGING_INFORMATION_HOST = 0x400
WBEM_STATUS_LOGGING_INFORMATION_REPOSITORY = 0x800
WBEM_STATUS_LOGGING_INFORMATION_ESS = 0x1000

class tag_WBEM_STATUS_TYPE(enum.Enum):
    WBEM_STATUS_COMPLETE = 0
    WBEM_STATUS_REQUIREMENTS = 1
    WBEM_STATUS_PROGRESS = 2
    WBEM_STATUS_LOGGING_INFORMATION = 0x100
    WBEM_STATUS_LOGGING_INFORMATION_PROVIDER = 0x200
    WBEM_STATUS_LOGGING_INFORMATION_HOST = 0x400
    WBEM_STATUS_LOGGING_INFORMATION_REPOSITORY = 0x800
    WBEM_STATUS_LOGGING_INFORMATION_ESS = 0x1000

WBEM_NO_WAIT = 0
WBEM_INFINITE = 0xffffffff

class tag_WBEM_TIMEOUT_TYPE(enum.Enum):
    WBEM_NO_WAIT = 0
    WBEM_INFINITE = 0xffffffff

WBEM_FLAG_ALWAYS = 0
WBEM_FLAG_ONLY_IF_TRUE = 0x1
WBEM_FLAG_ONLY_IF_FALSE = 0x2
WBEM_FLAG_ONLY_IF_IDENTICAL = 0x3
WBEM_MASK_PRIMARY_CONDITION = 0x3
WBEM_FLAG_KEYS_ONLY = 0x4
WBEM_FLAG_REFS_ONLY = 0x8
WBEM_FLAG_LOCAL_ONLY = 0x10
WBEM_FLAG_PROPAGATED_ONLY = 0x20
WBEM_FLAG_SYSTEM_ONLY = 0x30
WBEM_FLAG_NONSYSTEM_ONLY = 0x40
WBEM_MASK_CONDITION_ORIGIN = 0x70
WBEM_FLAG_CLASS_OVERRIDES_ONLY = 0x100
WBEM_FLAG_CLASS_LOCAL_AND_OVERRIDES = 0x200
WBEM_MASK_CLASS_CONDITION = 0x300

class tag_WBEM_CONDITION_FLAG_TYPE(enum.Enum):
    WBEM_FLAG_ALWAYS = 0
    WBEM_FLAG_ONLY_IF_TRUE = 0x1
    WBEM_FLAG_ONLY_IF_FALSE = 0x2
    WBEM_FLAG_ONLY_IF_IDENTICAL = 0x3
    WBEM_MASK_PRIMARY_CONDITION = 0x3
    WBEM_FLAG_KEYS_ONLY = 0x4
    WBEM_FLAG_REFS_ONLY = 0x8
    WBEM_FLAG_LOCAL_ONLY = 0x10
    WBEM_FLAG_PROPAGATED_ONLY = 0x20
    WBEM_FLAG_SYSTEM_ONLY = 0x30
    WBEM_FLAG_NONSYSTEM_ONLY = 0x40
    WBEM_MASK_CONDITION_ORIGIN = 0x70
    WBEM_FLAG_CLASS_OVERRIDES_ONLY = 0x100
    WBEM_FLAG_CLASS_LOCAL_AND_OVERRIDES = 0x200
    WBEM_MASK_CLASS_CONDITION = 0x300

WBEM_FLAVOR_DONT_PROPAGATE = 0
WBEM_FLAVOR_FLAG_PROPAGATE_TO_INSTANCE = 0x1
WBEM_FLAVOR_FLAG_PROPAGATE_TO_DERIVED_CLASS = 0x2
WBEM_FLAVOR_MASK_PROPAGATION = 0xf
WBEM_FLAVOR_OVERRIDABLE = 0
WBEM_FLAVOR_NOT_OVERRIDABLE = 0x10
WBEM_FLAVOR_MASK_PERMISSIONS = 0x10
WBEM_FLAVOR_ORIGIN_LOCAL = 0
WBEM_FLAVOR_ORIGIN_PROPAGATED = 0x20
WBEM_FLAVOR_ORIGIN_SYSTEM = 0x40
WBEM_FLAVOR_MASK_ORIGIN = 0x60
WBEM_FLAVOR_NOT_AMENDED = 0
WBEM_FLAVOR_AMENDED = 0x80
WBEM_FLAVOR_MASK_AMENDED = 0x80

class tag_WBEM_FLAVOR_TYPE(enum.Enum):
    WBEM_FLAVOR_DONT_PROPAGATE = 0
    WBEM_FLAVOR_FLAG_PROPAGATE_TO_INSTANCE = 0x1
    WBEM_FLAVOR_FLAG_PROPAGATE_TO_DERIVED_CLASS = 0x2
    WBEM_FLAVOR_MASK_PROPAGATION = 0xf
    WBEM_FLAVOR_OVERRIDABLE = 0
    WBEM_FLAVOR_NOT_OVERRIDABLE = 0x10
    WBEM_FLAVOR_MASK_PERMISSIONS = 0x10
    WBEM_FLAVOR_ORIGIN_LOCAL = 0
    WBEM_FLAVOR_ORIGIN_PROPAGATED = 0x20
    WBEM_FLAVOR_ORIGIN_SYSTEM = 0x40
    WBEM_FLAVOR_MASK_ORIGIN = 0x60
    WBEM_FLAVOR_NOT_AMENDED = 0
    WBEM_FLAVOR_AMENDED = 0x80
    WBEM_FLAVOR_MASK_AMENDED = 0x80

WBEM_FLAG_DEEP = 0
WBEM_FLAG_SHALLOW = 1
WBEM_FLAG_PROTOTYPE = 2

class tag_WBEM_QUERY_FLAG_TYPE(enum.Enum):
    WBEM_FLAG_DEEP = 0
    WBEM_FLAG_SHALLOW = 1
    WBEM_FLAG_PROTOTYPE = 2

WBEM_ENABLE = 1
WBEM_METHOD_EXECUTE = 2
WBEM_FULL_WRITE_REP = 4
WBEM_PARTIAL_WRITE_REP = 8
WBEM_WRITE_PROVIDER = 0x10
WBEM_REMOTE_ACCESS = 0x20
WBEM_RIGHT_SUBSCRIBE = 0x40
WBEM_RIGHT_PUBLISH = 0x80

class tag_WBEM_SECURITY_FLAGS(enum.Enum):
    WBEM_ENABLE = 1
    WBEM_METHOD_EXECUTE = 2
    WBEM_FULL_WRITE_REP = 4
    WBEM_PARTIAL_WRITE_REP = 8
    WBEM_WRITE_PROVIDER = 0x10
    WBEM_REMOTE_ACCESS = 0x20
    WBEM_RIGHT_SUBSCRIBE = 0x40
    WBEM_RIGHT_PUBLISH = 0x80

WBEM_FLAG_EXCLUDE_OBJECT_QUALIFIERS = 0x10
WBEM_FLAG_EXCLUDE_PROPERTY_QUALIFIERS = 0x20

class tag_WBEM_LIMITATION_FLAG_TYPE(enum.Enum):
    WBEM_FLAG_EXCLUDE_OBJECT_QUALIFIERS = 0x10
    WBEM_FLAG_EXCLUDE_PROPERTY_QUALIFIERS = 0x20

WBEM_FLAG_NO_FLAVORS = 0x1

class tag_WBEM_TEXT_FLAG_TYPE(enum.Enum):
    WBEM_FLAG_NO_FLAVORS = 0x1

WBEM_COMPARISON_INCLUDE_ALL = 0
WBEM_FLAG_IGNORE_QUALIFIERS = 0x1
WBEM_FLAG_IGNORE_OBJECT_SOURCE = 0x2
WBEM_FLAG_IGNORE_DEFAULT_VALUES = 0x4
WBEM_FLAG_IGNORE_CLASS = 0x8
WBEM_FLAG_IGNORE_CASE = 0x10
WBEM_FLAG_IGNORE_FLAVOR = 0x20

class tag_WBEM_COMPARISON_FLAG(enum.Enum):
    WBEM_COMPARISON_INCLUDE_ALL = 0
    WBEM_FLAG_IGNORE_QUALIFIERS = 0x1
    WBEM_FLAG_IGNORE_OBJECT_SOURCE = 0x2
    WBEM_FLAG_IGNORE_DEFAULT_VALUES = 0x4
    WBEM_FLAG_IGNORE_CLASS = 0x8
    WBEM_FLAG_IGNORE_CASE = 0x10
    WBEM_FLAG_IGNORE_FLAVOR = 0x20

WBEM_FLAG_ALLOW_READ = 0x1

class tag_WBEM_LOCKING(enum.Enum):
    WBEM_FLAG_ALLOW_READ = 0x1

CIM_ILLEGAL = 0xfff
CIM_EMPTY = 0
CIM_SINT8 = 16
CIM_UINT8 = 17
CIM_SINT16 = 2
CIM_UINT16 = 18
CIM_SINT32 = 3
CIM_UINT32 = 19
CIM_SINT64 = 20
CIM_UINT64 = 21
CIM_REAL32 = 4
CIM_REAL64 = 5
CIM_BOOLEAN = 11
CIM_STRING = 8
CIM_DATETIME = 101
CIM_REFERENCE = 102
CIM_CHAR16 = 103
CIM_OBJECT = 13
CIM_FLAG_ARRAY = 0x2000

class tag_CIMTYPE_ENUMERATION(enum.Enum):
    CIM_ILLEGAL = 0xfff
    CIM_EMPTY = 0
    CIM_SINT8 = 16
    CIM_UINT8 = 17
    CIM_SINT16 = 2
    CIM_UINT16 = 18
    CIM_SINT32 = 3
    CIM_UINT32 = 19
    CIM_SINT64 = 20
    CIM_UINT64 = 21
    CIM_REAL32 = 4
    CIM_REAL64 = 5
    CIM_BOOLEAN = 11
    CIM_STRING = 8
    CIM_DATETIME = 101
    CIM_REFERENCE = 102
    CIM_CHAR16 = 103
    CIM_OBJECT = 13
    CIM_FLAG_ARRAY = 0x2000

WBEM_FLAG_BACKUP_RESTORE_DEFAULT = 0
WBEM_FLAG_BACKUP_RESTORE_FORCE_SHUTDOWN = 1

class tag_WBEM_BACKUP_RESTORE_FLAGS(enum.Enum):
    WBEM_FLAG_BACKUP_RESTORE_DEFAULT = 0
    WBEM_FLAG_BACKUP_RESTORE_FORCE_SHUTDOWN = 1

WBEM_FLAG_REFRESH_AUTO_RECONNECT = 0
WBEM_FLAG_REFRESH_NO_AUTO_RECONNECT = 1

class tag_WBEM_REFRESHER_FLAGS(enum.Enum):
    WBEM_FLAG_REFRESH_AUTO_RECONNECT = 0
    WBEM_FLAG_REFRESH_NO_AUTO_RECONNECT = 1

WBEM_SHUTDOWN_UNLOAD_COMPONENT = 1
WBEM_SHUTDOWN_WMI = 2
WBEM_SHUTDOWN_OS = 3

class tag_WBEM_SHUTDOWN_FLAGS(enum.Enum):
    WBEM_SHUTDOWN_UNLOAD_COMPONENT = 1
    WBEM_SHUTDOWN_WMI = 2
    WBEM_SHUTDOWN_OS = 3

WBEMSTATUS_FORMAT_NEWLINE = 0
WBEMSTATUS_FORMAT_NO_NEWLINE = 1

class tag_WBEMSTATUS_FORMAT(enum.Enum):
    WBEMSTATUS_FORMAT_NEWLINE = 0
    WBEMSTATUS_FORMAT_NO_NEWLINE = 1

WBEM_MAX_IDENTIFIER = 0x1000
WBEM_MAX_QUERY = 0x4000
WBEM_MAX_PATH = 0x2000
WBEM_MAX_OBJECT_NESTING = 64
WBEM_MAX_USER_PROPERTIES = 1024

class tag_WBEM_LIMITS(enum.Enum):
    WBEM_MAX_IDENTIFIER = 0x1000
    WBEM_MAX_QUERY = 0x4000
    WBEM_MAX_PATH = 0x2000
    WBEM_MAX_OBJECT_NESTING = 64
    WBEM_MAX_USER_PROPERTIES = 1024

WBEM_NO_ERROR = 0
WBEM_S_NO_ERROR = 0
WBEM_S_SAME = 0
WBEM_S_FALSE = 1
WBEM_S_ALREADY_EXISTS = 0x40001
WBEM_S_RESET_TO_DEFAULT = 0x40002
WBEM_S_DIFFERENT = 0x40003
WBEM_S_TIMEDOUT = 0x40004
WBEM_S_NO_MORE_DATA = 0x40005
WBEM_S_OPERATION_CANCELLED = 0x40006
WBEM_S_PENDING = 0x40007
WBEM_S_DUPLICATE_OBJECTS = 0x40008
WBEM_S_ACCESS_DENIED = 0x40009
WBEM_S_PARTIAL_RESULTS = 0x40010
WBEM_S_SOURCE_NOT_AVAILABLE = 0x40017
WBEM_E_FAILED = 0x80041001
WBEM_E_NOT_FOUND = 0x80041002
WBEM_E_ACCESS_DENIED = 0x80041003
WBEM_E_PROVIDER_FAILURE = 0x80041004
WBEM_E_TYPE_MISMATCH = 0x80041005
WBEM_E_OUT_OF_MEMORY = 0x80041006
WBEM_E_INVALID_CONTEXT = 0x80041007
WBEM_E_INVALID_PARAMETER = 0x80041008
WBEM_E_NOT_AVAILABLE = 0x80041009
WBEM_E_CRITICAL_ERROR = 0x8004100a
WBEM_E_INVALID_STREAM = 0x8004100b
WBEM_E_NOT_SUPPORTED = 0x8004100c
WBEM_E_INVALID_SUPERCLASS = 0x8004100d
WBEM_E_INVALID_NAMESPACE = 0x8004100e
WBEM_E_INVALID_OBJECT = 0x8004100f
WBEM_E_INVALID_CLASS = 0x80041010
WBEM_E_PROVIDER_NOT_FOUND = 0x80041011
WBEM_E_INVALID_PROVIDER_REGISTRATION = 0x80041012
WBEM_E_PROVIDER_LOAD_FAILURE = 0x80041013
WBEM_E_INITIALIZATION_FAILURE = 0x80041014
WBEM_E_TRANSPORT_FAILURE = 0x80041015
WBEM_E_INVALID_OPERATION = 0x80041016
WBEM_E_INVALID_QUERY = 0x80041017
WBEM_E_INVALID_QUERY_TYPE = 0x80041018
WBEM_E_ALREADY_EXISTS = 0x80041019
WBEM_E_OVERRIDE_NOT_ALLOWED = 0x8004101a
WBEM_E_PROPAGATED_QUALIFIER = 0x8004101b
WBEM_E_PROPAGATED_PROPERTY = 0x8004101c
WBEM_E_UNEXPECTED = 0x8004101d
WBEM_E_ILLEGAL_OPERATION = 0x8004101e
WBEM_E_CANNOT_BE_KEY = 0x8004101f
WBEM_E_INCOMPLETE_CLASS = 0x80041020
WBEM_E_INVALID_SYNTAX = 0x80041021
WBEM_E_NONDECORATED_OBJECT = 0x80041022
WBEM_E_READ_ONLY = 0x80041023
WBEM_E_PROVIDER_NOT_CAPABLE = 0x80041024
WBEM_E_CLASS_HAS_CHILDREN = 0x80041025
WBEM_E_CLASS_HAS_INSTANCES = 0x80041026
WBEM_E_QUERY_NOT_IMPLEMENTED = 0x80041027
WBEM_E_ILLEGAL_NULL = 0x80041028
WBEM_E_INVALID_QUALIFIER_TYPE = 0x80041029
WBEM_E_INVALID_PROPERTY_TYPE = 0x8004102a
WBEM_E_VALUE_OUT_OF_RANGE = 0x8004102b
WBEM_E_CANNOT_BE_SINGLETON = 0x8004102c
WBEM_E_INVALID_CIM_TYPE = 0x8004102d
WBEM_E_INVALID_METHOD = 0x8004102e
WBEM_E_INVALID_METHOD_PARAMETERS = 0x8004102f
WBEM_E_SYSTEM_PROPERTY = 0x80041030
WBEM_E_INVALID_PROPERTY = 0x80041031
WBEM_E_CALL_CANCELLED = 0x80041032
WBEM_E_SHUTTING_DOWN = 0x80041033
WBEM_E_PROPAGATED_METHOD = 0x80041034
WBEM_E_UNSUPPORTED_PARAMETER = 0x80041035
WBEM_E_MISSING_PARAMETER_ID = 0x80041036
WBEM_E_INVALID_PARAMETER_ID = 0x80041037
WBEM_E_NONCONSECUTIVE_PARAMETER_IDS = 0x80041038
WBEM_E_PARAMETER_ID_ON_RETVAL = 0x80041039
WBEM_E_INVALID_OBJECT_PATH = 0x8004103a
WBEM_E_OUT_OF_DISK_SPACE = 0x8004103b
WBEM_E_BUFFER_TOO_SMALL = 0x8004103c
WBEM_E_UNSUPPORTED_PUT_EXTENSION = 0x8004103d
WBEM_E_UNKNOWN_OBJECT_TYPE = 0x8004103e
WBEM_E_UNKNOWN_PACKET_TYPE = 0x8004103f
WBEM_E_MARSHAL_VERSION_MISMATCH = 0x80041040
WBEM_E_MARSHAL_INVALID_SIGNATURE = 0x80041041
WBEM_E_INVALID_QUALIFIER = 0x80041042
WBEM_E_INVALID_DUPLICATE_PARAMETER = 0x80041043
WBEM_E_TOO_MUCH_DATA = 0x80041044
WBEM_E_SERVER_TOO_BUSY = 0x80041045
WBEM_E_INVALID_FLAVOR = 0x80041046
WBEM_E_CIRCULAR_REFERENCE = 0x80041047
WBEM_E_UNSUPPORTED_CLASS_UPDATE = 0x80041048
WBEM_E_CANNOT_CHANGE_KEY_INHERITANCE = 0x80041049
WBEM_E_CANNOT_CHANGE_INDEX_INHERITANCE = 0x80041050
WBEM_E_TOO_MANY_PROPERTIES = 0x80041051
WBEM_E_UPDATE_TYPE_MISMATCH = 0x80041052
WBEM_E_UPDATE_OVERRIDE_NOT_ALLOWED = 0x80041053
WBEM_E_UPDATE_PROPAGATED_METHOD = 0x80041054
WBEM_E_METHOD_NOT_IMPLEMENTED = 0x80041055
WBEM_E_METHOD_DISABLED = 0x80041056
WBEM_E_REFRESHER_BUSY = 0x80041057
WBEM_E_UNPARSABLE_QUERY = 0x80041058
WBEM_E_NOT_EVENT_CLASS = 0x80041059
WBEM_E_MISSING_GROUP_WITHIN = 0x8004105a
WBEM_E_MISSING_AGGREGATION_LIST = 0x8004105b
WBEM_E_PROPERTY_NOT_AN_OBJECT = 0x8004105c
WBEM_E_AGGREGATING_BY_OBJECT = 0x8004105d
WBEM_E_UNINTERPRETABLE_PROVIDER_QUERY = 0x8004105f
WBEM_E_BACKUP_RESTORE_WINMGMT_RUNNING = 0x80041060
WBEM_E_QUEUE_OVERFLOW = 0x80041061
WBEM_E_PRIVILEGE_NOT_HELD = 0x80041062
WBEM_E_INVALID_OPERATOR = 0x80041063
WBEM_E_LOCAL_CREDENTIALS = 0x80041064
WBEM_E_CANNOT_BE_ABSTRACT = 0x80041065
WBEM_E_AMENDED_OBJECT = 0x80041066
WBEM_E_CLIENT_TOO_SLOW = 0x80041067
WBEM_E_NULL_SECURITY_DESCRIPTOR = 0x80041068
WBEM_E_TIMED_OUT = 0x80041069
WBEM_E_INVALID_ASSOCIATION = 0x8004106a
WBEM_E_AMBIGUOUS_OPERATION = 0x8004106b
WBEM_E_QUOTA_VIOLATION = 0x8004106c
WBEM_E_RESERVED_001 = 0x8004106d
WBEM_E_RESERVED_002 = 0x8004106e
WBEM_E_UNSUPPORTED_LOCALE = 0x8004106f
WBEM_E_HANDLE_OUT_OF_DATE = 0x80041070
WBEM_E_CONNECTION_FAILED = 0x80041071
WBEM_E_INVALID_HANDLE_REQUEST = 0x80041072
WBEM_E_PROPERTY_NAME_TOO_WIDE = 0x80041073
WBEM_E_CLASS_NAME_TOO_WIDE = 0x80041074
WBEM_E_METHOD_NAME_TOO_WIDE = 0x80041075
WBEM_E_QUALIFIER_NAME_TOO_WIDE = 0x80041076
WBEM_E_RERUN_COMMAND = 0x80041077
WBEM_E_DATABASE_VER_MISMATCH = 0x80041078
WBEM_E_VETO_DELETE = 0x80041079
WBEM_E_VETO_PUT = 0x8004107a
WBEM_E_INVALID_LOCALE = 0x80041080
WBEM_E_PROVIDER_SUSPENDED = 0x80041081
WBEM_E_SYNCHRONIZATION_REQUIRED = 0x80041082
WBEM_E_NO_SCHEMA = 0x80041083
WBEM_E_PROVIDER_ALREADY_REGISTERED = 0x80041084
WBEM_E_PROVIDER_NOT_REGISTERED = 0x80041085
WBEM_E_FATAL_TRANSPORT_ERROR = 0x80041086
WBEM_E_ENCRYPTED_CONNECTION_REQUIRED = 0x80041087
WBEM_E_PROVIDER_TIMED_OUT = 0x80041088
WBEM_E_NO_KEY = 0x80041089
WBEM_E_PROVIDER_DISABLED = 0x8004108a
WBEMESS_E_REGISTRATION_TOO_BROAD = 0x80042001
WBEMESS_E_REGISTRATION_TOO_PRECISE = 0x80042002
WBEMESS_E_AUTHZ_NOT_PRIVILEGED = 0x80042003
WBEMMOF_E_EXPECTED_QUALIFIER_NAME = 0x80044001
WBEMMOF_E_EXPECTED_SEMI = 0x80044002
WBEMMOF_E_EXPECTED_OPEN_BRACE = 0x80044003
WBEMMOF_E_EXPECTED_CLOSE_BRACE = 0x80044004
WBEMMOF_E_EXPECTED_CLOSE_BRACKET = 0x80044005
WBEMMOF_E_EXPECTED_CLOSE_PAREN = 0x80044006
WBEMMOF_E_ILLEGAL_CONSTANT_VALUE = 0x80044007
WBEMMOF_E_EXPECTED_TYPE_IDENTIFIER = 0x80044008
WBEMMOF_E_EXPECTED_OPEN_PAREN = 0x80044009
WBEMMOF_E_UNRECOGNIZED_TOKEN = 0x8004400a
WBEMMOF_E_UNRECOGNIZED_TYPE = 0x8004400b
WBEMMOF_E_EXPECTED_PROPERTY_NAME = 0x8004400c
WBEMMOF_E_TYPEDEF_NOT_SUPPORTED = 0x8004400d
WBEMMOF_E_UNEXPECTED_ALIAS = 0x8004400e
WBEMMOF_E_UNEXPECTED_ARRAY_INIT = 0x8004400f
WBEMMOF_E_INVALID_AMENDMENT_SYNTAX = 0x80044010
WBEMMOF_E_INVALID_DUPLICATE_AMENDMENT = 0x80044011
WBEMMOF_E_INVALID_PRAGMA = 0x80044012
WBEMMOF_E_INVALID_NAMESPACE_SYNTAX = 0x80044013
WBEMMOF_E_EXPECTED_CLASS_NAME = 0x80044014
WBEMMOF_E_TYPE_MISMATCH = 0x80044015
WBEMMOF_E_EXPECTED_ALIAS_NAME = 0x80044016
WBEMMOF_E_INVALID_CLASS_DECLARATION = 0x80044017
WBEMMOF_E_INVALID_INSTANCE_DECLARATION = 0x80044018
WBEMMOF_E_EXPECTED_DOLLAR = 0x80044019
WBEMMOF_E_CIMTYPE_QUALIFIER = 0x8004401a
WBEMMOF_E_DUPLICATE_PROPERTY = 0x8004401b
WBEMMOF_E_INVALID_NAMESPACE_SPECIFICATION = 0x8004401c
WBEMMOF_E_OUT_OF_RANGE = 0x8004401d
WBEMMOF_E_INVALID_FILE = 0x8004401e
WBEMMOF_E_ALIASES_IN_EMBEDDED = 0x8004401f
WBEMMOF_E_NULL_ARRAY_ELEM = 0x80044020
WBEMMOF_E_DUPLICATE_QUALIFIER = 0x80044021
WBEMMOF_E_EXPECTED_FLAVOR_TYPE = 0x80044022
WBEMMOF_E_INCOMPATIBLE_FLAVOR_TYPES = 0x80044023
WBEMMOF_E_MULTIPLE_ALIASES = 0x80044024
WBEMMOF_E_INCOMPATIBLE_FLAVOR_TYPES2 = 0x80044025
WBEMMOF_E_NO_ARRAYS_RETURNED = 0x80044026
WBEMMOF_E_MUST_BE_IN_OR_OUT = 0x80044027
WBEMMOF_E_INVALID_FLAGS_SYNTAX = 0x80044028
WBEMMOF_E_EXPECTED_BRACE_OR_BAD_TYPE = 0x80044029
WBEMMOF_E_UNSUPPORTED_CIMV22_QUAL_VALUE = 0x8004402a
WBEMMOF_E_UNSUPPORTED_CIMV22_DATA_TYPE = 0x8004402b
WBEMMOF_E_INVALID_DELETEINSTANCE_SYNTAX = 0x8004402c
WBEMMOF_E_INVALID_QUALIFIER_SYNTAX = 0x8004402d
WBEMMOF_E_QUALIFIER_USED_OUTSIDE_SCOPE = 0x8004402e
WBEMMOF_E_ERROR_CREATING_TEMP_FILE = 0x8004402f
WBEMMOF_E_ERROR_INVALID_INCLUDE_FILE = 0x80044030
WBEMMOF_E_INVALID_DELETECLASS_SYNTAX = 0x80044031

class tag_WBEMSTATUS(enum.Enum):
    WBEM_NO_ERROR = 0
    WBEM_S_NO_ERROR = 0
    WBEM_S_SAME = 0
    WBEM_S_FALSE = 1
    WBEM_S_ALREADY_EXISTS = 0x40001
    WBEM_S_RESET_TO_DEFAULT = 0x40002
    WBEM_S_DIFFERENT = 0x40003
    WBEM_S_TIMEDOUT = 0x40004
    WBEM_S_NO_MORE_DATA = 0x40005
    WBEM_S_OPERATION_CANCELLED = 0x40006
    WBEM_S_PENDING = 0x40007
    WBEM_S_DUPLICATE_OBJECTS = 0x40008
    WBEM_S_ACCESS_DENIED = 0x40009
    WBEM_S_PARTIAL_RESULTS = 0x40010
    WBEM_S_SOURCE_NOT_AVAILABLE = 0x40017
    WBEM_E_FAILED = 0x80041001
    WBEM_E_NOT_FOUND = 0x80041002
    WBEM_E_ACCESS_DENIED = 0x80041003
    WBEM_E_PROVIDER_FAILURE = 0x80041004
    WBEM_E_TYPE_MISMATCH = 0x80041005
    WBEM_E_OUT_OF_MEMORY = 0x80041006
    WBEM_E_INVALID_CONTEXT = 0x80041007
    WBEM_E_INVALID_PARAMETER = 0x80041008
    WBEM_E_NOT_AVAILABLE = 0x80041009
    WBEM_E_CRITICAL_ERROR = 0x8004100a
    WBEM_E_INVALID_STREAM = 0x8004100b
    WBEM_E_NOT_SUPPORTED = 0x8004100c
    WBEM_E_INVALID_SUPERCLASS = 0x8004100d
    WBEM_E_INVALID_NAMESPACE = 0x8004100e
    WBEM_E_INVALID_OBJECT = 0x8004100f
    WBEM_E_INVALID_CLASS = 0x80041010
    WBEM_E_PROVIDER_NOT_FOUND = 0x80041011
    WBEM_E_INVALID_PROVIDER_REGISTRATION = 0x80041012
    WBEM_E_PROVIDER_LOAD_FAILURE = 0x80041013
    WBEM_E_INITIALIZATION_FAILURE = 0x80041014
    WBEM_E_TRANSPORT_FAILURE = 0x80041015
    WBEM_E_INVALID_OPERATION = 0x80041016
    WBEM_E_INVALID_QUERY = 0x80041017
    WBEM_E_INVALID_QUERY_TYPE = 0x80041018
    WBEM_E_ALREADY_EXISTS = 0x80041019
    WBEM_E_OVERRIDE_NOT_ALLOWED = 0x8004101a
    WBEM_E_PROPAGATED_QUALIFIER = 0x8004101b
    WBEM_E_PROPAGATED_PROPERTY = 0x8004101c
    WBEM_E_UNEXPECTED = 0x8004101d
    WBEM_E_ILLEGAL_OPERATION = 0x8004101e
    WBEM_E_CANNOT_BE_KEY = 0x8004101f
    WBEM_E_INCOMPLETE_CLASS = 0x80041020
    WBEM_E_INVALID_SYNTAX = 0x80041021
    WBEM_E_NONDECORATED_OBJECT = 0x80041022
    WBEM_E_READ_ONLY = 0x80041023
    WBEM_E_PROVIDER_NOT_CAPABLE = 0x80041024
    WBEM_E_CLASS_HAS_CHILDREN = 0x80041025
    WBEM_E_CLASS_HAS_INSTANCES = 0x80041026
    WBEM_E_QUERY_NOT_IMPLEMENTED = 0x80041027
    WBEM_E_ILLEGAL_NULL = 0x80041028
    WBEM_E_INVALID_QUALIFIER_TYPE = 0x80041029
    WBEM_E_INVALID_PROPERTY_TYPE = 0x8004102a
    WBEM_E_VALUE_OUT_OF_RANGE = 0x8004102b
    WBEM_E_CANNOT_BE_SINGLETON = 0x8004102c
    WBEM_E_INVALID_CIM_TYPE = 0x8004102d
    WBEM_E_INVALID_METHOD = 0x8004102e
    WBEM_E_INVALID_METHOD_PARAMETERS = 0x8004102f
    WBEM_E_SYSTEM_PROPERTY = 0x80041030
    WBEM_E_INVALID_PROPERTY = 0x80041031
    WBEM_E_CALL_CANCELLED = 0x80041032
    WBEM_E_SHUTTING_DOWN = 0x80041033
    WBEM_E_PROPAGATED_METHOD = 0x80041034
    WBEM_E_UNSUPPORTED_PARAMETER = 0x80041035
    WBEM_E_MISSING_PARAMETER_ID = 0x80041036
    WBEM_E_INVALID_PARAMETER_ID = 0x80041037
    WBEM_E_NONCONSECUTIVE_PARAMETER_IDS = 0x80041038
    WBEM_E_PARAMETER_ID_ON_RETVAL = 0x80041039
    WBEM_E_INVALID_OBJECT_PATH = 0x8004103a
    WBEM_E_OUT_OF_DISK_SPACE = 0x8004103b
    WBEM_E_BUFFER_TOO_SMALL = 0x8004103c
    WBEM_E_UNSUPPORTED_PUT_EXTENSION = 0x8004103d
    WBEM_E_UNKNOWN_OBJECT_TYPE = 0x8004103e
    WBEM_E_UNKNOWN_PACKET_TYPE = 0x8004103f
    WBEM_E_MARSHAL_VERSION_MISMATCH = 0x80041040
    WBEM_E_MARSHAL_INVALID_SIGNATURE = 0x80041041
    WBEM_E_INVALID_QUALIFIER = 0x80041042
    WBEM_E_INVALID_DUPLICATE_PARAMETER = 0x80041043
    WBEM_E_TOO_MUCH_DATA = 0x80041044
    WBEM_E_SERVER_TOO_BUSY = 0x80041045
    WBEM_E_INVALID_FLAVOR = 0x80041046
    WBEM_E_CIRCULAR_REFERENCE = 0x80041047
    WBEM_E_UNSUPPORTED_CLASS_UPDATE = 0x80041048
    WBEM_E_CANNOT_CHANGE_KEY_INHERITANCE = 0x80041049
    WBEM_E_CANNOT_CHANGE_INDEX_INHERITANCE = 0x80041050
    WBEM_E_TOO_MANY_PROPERTIES = 0x80041051
    WBEM_E_UPDATE_TYPE_MISMATCH = 0x80041052
    WBEM_E_UPDATE_OVERRIDE_NOT_ALLOWED = 0x80041053
    WBEM_E_UPDATE_PROPAGATED_METHOD = 0x80041054
    WBEM_E_METHOD_NOT_IMPLEMENTED = 0x80041055
    WBEM_E_METHOD_DISABLED = 0x80041056
    WBEM_E_REFRESHER_BUSY = 0x80041057
    WBEM_E_UNPARSABLE_QUERY = 0x80041058
    WBEM_E_NOT_EVENT_CLASS = 0x80041059
    WBEM_E_MISSING_GROUP_WITHIN = 0x8004105a
    WBEM_E_MISSING_AGGREGATION_LIST = 0x8004105b
    WBEM_E_PROPERTY_NOT_AN_OBJECT = 0x8004105c
    WBEM_E_AGGREGATING_BY_OBJECT = 0x8004105d
    WBEM_E_UNINTERPRETABLE_PROVIDER_QUERY = 0x8004105f
    WBEM_E_BACKUP_RESTORE_WINMGMT_RUNNING = 0x80041060
    WBEM_E_QUEUE_OVERFLOW = 0x80041061
    WBEM_E_PRIVILEGE_NOT_HELD = 0x80041062
    WBEM_E_INVALID_OPERATOR = 0x80041063
    WBEM_E_LOCAL_CREDENTIALS = 0x80041064
    WBEM_E_CANNOT_BE_ABSTRACT = 0x80041065
    WBEM_E_AMENDED_OBJECT = 0x80041066
    WBEM_E_CLIENT_TOO_SLOW = 0x80041067
    WBEM_E_NULL_SECURITY_DESCRIPTOR = 0x80041068
    WBEM_E_TIMED_OUT = 0x80041069
    WBEM_E_INVALID_ASSOCIATION = 0x8004106a
    WBEM_E_AMBIGUOUS_OPERATION = 0x8004106b
    WBEM_E_QUOTA_VIOLATION = 0x8004106c
    WBEM_E_RESERVED_001 = 0x8004106d
    WBEM_E_RESERVED_002 = 0x8004106e
    WBEM_E_UNSUPPORTED_LOCALE = 0x8004106f
    WBEM_E_HANDLE_OUT_OF_DATE = 0x80041070
    WBEM_E_CONNECTION_FAILED = 0x80041071
    WBEM_E_INVALID_HANDLE_REQUEST = 0x80041072
    WBEM_E_PROPERTY_NAME_TOO_WIDE = 0x80041073
    WBEM_E_CLASS_NAME_TOO_WIDE = 0x80041074
    WBEM_E_METHOD_NAME_TOO_WIDE = 0x80041075
    WBEM_E_QUALIFIER_NAME_TOO_WIDE = 0x80041076
    WBEM_E_RERUN_COMMAND = 0x80041077
    WBEM_E_DATABASE_VER_MISMATCH = 0x80041078
    WBEM_E_VETO_DELETE = 0x80041079
    WBEM_E_VETO_PUT = 0x8004107a
    WBEM_E_INVALID_LOCALE = 0x80041080
    WBEM_E_PROVIDER_SUSPENDED = 0x80041081
    WBEM_E_SYNCHRONIZATION_REQUIRED = 0x80041082
    WBEM_E_NO_SCHEMA = 0x80041083
    WBEM_E_PROVIDER_ALREADY_REGISTERED = 0x80041084
    WBEM_E_PROVIDER_NOT_REGISTERED = 0x80041085
    WBEM_E_FATAL_TRANSPORT_ERROR = 0x80041086
    WBEM_E_ENCRYPTED_CONNECTION_REQUIRED = 0x80041087
    WBEM_E_PROVIDER_TIMED_OUT = 0x80041088
    WBEM_E_NO_KEY = 0x80041089
    WBEM_E_PROVIDER_DISABLED = 0x8004108a
    WBEMESS_E_REGISTRATION_TOO_BROAD = 0x80042001
    WBEMESS_E_REGISTRATION_TOO_PRECISE = 0x80042002
    WBEMESS_E_AUTHZ_NOT_PRIVILEGED = 0x80042003
    WBEMMOF_E_EXPECTED_QUALIFIER_NAME = 0x80044001
    WBEMMOF_E_EXPECTED_SEMI = 0x80044002
    WBEMMOF_E_EXPECTED_OPEN_BRACE = 0x80044003
    WBEMMOF_E_EXPECTED_CLOSE_BRACE = 0x80044004
    WBEMMOF_E_EXPECTED_CLOSE_BRACKET = 0x80044005
    WBEMMOF_E_EXPECTED_CLOSE_PAREN = 0x80044006
    WBEMMOF_E_ILLEGAL_CONSTANT_VALUE = 0x80044007
    WBEMMOF_E_EXPECTED_TYPE_IDENTIFIER = 0x80044008
    WBEMMOF_E_EXPECTED_OPEN_PAREN = 0x80044009
    WBEMMOF_E_UNRECOGNIZED_TOKEN = 0x8004400a
    WBEMMOF_E_UNRECOGNIZED_TYPE = 0x8004400b
    WBEMMOF_E_EXPECTED_PROPERTY_NAME = 0x8004400c
    WBEMMOF_E_TYPEDEF_NOT_SUPPORTED = 0x8004400d
    WBEMMOF_E_UNEXPECTED_ALIAS = 0x8004400e
    WBEMMOF_E_UNEXPECTED_ARRAY_INIT = 0x8004400f
    WBEMMOF_E_INVALID_AMENDMENT_SYNTAX = 0x80044010
    WBEMMOF_E_INVALID_DUPLICATE_AMENDMENT = 0x80044011
    WBEMMOF_E_INVALID_PRAGMA = 0x80044012
    WBEMMOF_E_INVALID_NAMESPACE_SYNTAX = 0x80044013
    WBEMMOF_E_EXPECTED_CLASS_NAME = 0x80044014
    WBEMMOF_E_TYPE_MISMATCH = 0x80044015
    WBEMMOF_E_EXPECTED_ALIAS_NAME = 0x80044016
    WBEMMOF_E_INVALID_CLASS_DECLARATION = 0x80044017
    WBEMMOF_E_INVALID_INSTANCE_DECLARATION = 0x80044018
    WBEMMOF_E_EXPECTED_DOLLAR = 0x80044019
    WBEMMOF_E_CIMTYPE_QUALIFIER = 0x8004401a
    WBEMMOF_E_DUPLICATE_PROPERTY = 0x8004401b
    WBEMMOF_E_INVALID_NAMESPACE_SPECIFICATION = 0x8004401c
    WBEMMOF_E_OUT_OF_RANGE = 0x8004401d
    WBEMMOF_E_INVALID_FILE = 0x8004401e
    WBEMMOF_E_ALIASES_IN_EMBEDDED = 0x8004401f
    WBEMMOF_E_NULL_ARRAY_ELEM = 0x80044020
    WBEMMOF_E_DUPLICATE_QUALIFIER = 0x80044021
    WBEMMOF_E_EXPECTED_FLAVOR_TYPE = 0x80044022
    WBEMMOF_E_INCOMPATIBLE_FLAVOR_TYPES = 0x80044023
    WBEMMOF_E_MULTIPLE_ALIASES = 0x80044024
    WBEMMOF_E_INCOMPATIBLE_FLAVOR_TYPES2 = 0x80044025
    WBEMMOF_E_NO_ARRAYS_RETURNED = 0x80044026
    WBEMMOF_E_MUST_BE_IN_OR_OUT = 0x80044027
    WBEMMOF_E_INVALID_FLAGS_SYNTAX = 0x80044028
    WBEMMOF_E_EXPECTED_BRACE_OR_BAD_TYPE = 0x80044029
    WBEMMOF_E_UNSUPPORTED_CIMV22_QUAL_VALUE = 0x8004402a
    WBEMMOF_E_UNSUPPORTED_CIMV22_DATA_TYPE = 0x8004402b
    WBEMMOF_E_INVALID_DELETEINSTANCE_SYNTAX = 0x8004402c
    WBEMMOF_E_INVALID_QUALIFIER_SYNTAX = 0x8004402d
    WBEMMOF_E_QUALIFIER_USED_OUTSIDE_SCOPE = 0x8004402e
    WBEMMOF_E_ERROR_CREATING_TEMP_FILE = 0x8004402f
    WBEMMOF_E_ERROR_INVALID_INCLUDE_FILE = 0x80044030
    WBEMMOF_E_INVALID_DELETECLASS_SYNTAX = 0x80044031

WMI_OBJ_TEXT_CIM_DTD_2_0 = 1
WMI_OBJ_TEXT_WMI_DTD_2_0 = 2
WMI_OBJ_TEXT_WMI_EXT1 = 3
WMI_OBJ_TEXT_WMI_EXT2 = 4
WMI_OBJ_TEXT_WMI_EXT3 = 5
WMI_OBJ_TEXT_WMI_EXT4 = 6
WMI_OBJ_TEXT_WMI_EXT5 = 7
WMI_OBJ_TEXT_WMI_EXT6 = 8
WMI_OBJ_TEXT_WMI_EXT7 = 9
WMI_OBJ_TEXT_WMI_EXT8 = 10
WMI_OBJ_TEXT_WMI_EXT9 = 11
WMI_OBJ_TEXT_WMI_EXT10 = 12
WMI_OBJ_TEXT_LAST = 13

class tag_WMI_OBJ_TEXT(enum.Enum):
    WMI_OBJ_TEXT_CIM_DTD_2_0 = 1
    WMI_OBJ_TEXT_WMI_DTD_2_0 = 2
    WMI_OBJ_TEXT_WMI_EXT1 = 3
    WMI_OBJ_TEXT_WMI_EXT2 = 4
    WMI_OBJ_TEXT_WMI_EXT3 = 5
    WMI_OBJ_TEXT_WMI_EXT4 = 6
    WMI_OBJ_TEXT_WMI_EXT5 = 7
    WMI_OBJ_TEXT_WMI_EXT6 = 8
    WMI_OBJ_TEXT_WMI_EXT7 = 9
    WMI_OBJ_TEXT_WMI_EXT8 = 10
    WMI_OBJ_TEXT_WMI_EXT9 = 11
    WMI_OBJ_TEXT_WMI_EXT10 = 12
    WMI_OBJ_TEXT_LAST = 13

WBEM_FLAG_CHECK_ONLY = 0x1
WBEM_FLAG_AUTORECOVER = 0x2
WBEM_FLAG_WMI_CHECK = 0x4
WBEM_FLAG_CONSOLE_PRINT = 0x8
WBEM_FLAG_DONT_ADD_TO_LIST = 0x10
WBEM_FLAG_SPLIT_FILES = 0x20
WBEM_FLAG_STORE_FILE = 0x100

class tag_WBEM_COMPILER_OPTIONS(enum.Enum):
    WBEM_FLAG_CHECK_ONLY = 0x1
    WBEM_FLAG_AUTORECOVER = 0x2
    WBEM_FLAG_WMI_CHECK = 0x4
    WBEM_FLAG_CONSOLE_PRINT = 0x8
    WBEM_FLAG_DONT_ADD_TO_LIST = 0x10
    WBEM_FLAG_SPLIT_FILES = 0x20
    WBEM_FLAG_STORE_FILE = 0x100

WBEM_FLAG_CONNECT_REPOSITORY_ONLY = 0x40
WBEM_FLAG_CONNECT_USE_MAX_WAIT = 0x80
WBEM_FLAG_CONNECT_PROVIDERS = 0x100

class tag_WBEM_CONNECT_OPTIONS(enum.Enum):
    WBEM_FLAG_CONNECT_REPOSITORY_ONLY = 0x40
    WBEM_FLAG_CONNECT_USE_MAX_WAIT = 0x80
    WBEM_FLAG_CONNECT_PROVIDERS = 0x100

WBEM_FLAG_UNSECAPP_DEFAULT_CHECK_ACCESS = 0
WBEM_FLAG_UNSECAPP_CHECK_ACCESS = 1
WBEM_FLAG_UNSECAPP_DONT_CHECK_ACCESS = 2

class tag_WBEM_UNSECAPP_FLAG_TYPE(enum.Enum):
    WBEM_FLAG_UNSECAPP_DEFAULT_CHECK_ACCESS = 0
    WBEM_FLAG_UNSECAPP_CHECK_ACCESS = 1
    WBEM_FLAG_UNSECAPP_DONT_CHECK_ACCESS = 2

WBEM_FLAG_SHORT_NAME = 0x1
WBEM_FLAG_LONG_NAME = 0x2

class tag_WBEM_INFORMATION_FLAG_TYPE(enum.Enum):
    WBEM_FLAG_SHORT_NAME = 0x1
    WBEM_FLAG_LONG_NAME = 0x2

class tag_CompileStatusInfo(Structure):
    _fields_ = [
        ('lPhaseError', LONG),
        ('hRes', HRESULT),
        ('ObjectNum', LONG),
        ('FirstLine', LONG),
        ('LastLine', LONG),
        ('dwOutFlags', DWORD)
    ]

WBEM_COMPILE_STATUS_INFO = tag_CompileStatusInfo
CIMTYPE = LONG

CLSID_WbemBackupRestore = DEFINE_GUID(0xc49e32c6, 0xbc8b, 0x11d2, 0x85,0xd4, 0x00,0x10,0x5a,0x1f,0x83,0x04)
CLSID_WbemClassObject = DEFINE_GUID(0x9a653086, 0x174f, 0x11d2, 0xb5,0xf9, 0x00,0x10,0x4b,0x70,0x3e,0xfd)
CLSID_WbemContext = DEFINE_GUID(0x674b6698, 0xee92, 0x11d0, 0xad,0x71, 0x00,0xc0,0x4f,0xd8,0xfd,0xff)
CLSID_WbemLocator = DEFINE_GUID(0x4590f811, 0x1d3a, 0x11d0, 0x89,0x1f, 0x00,0xaa,0x00,0x4b,0x2e,0x24)
CLSID_WbemStatusCodeText = DEFINE_GUID(0xeb87e1bd, 0x3233, 0x11d2, 0xae,0xc9, 0x00,0xc0,0x4f,0xb6,0x88,0x20)
CLSID_UnsecuredApartment = DEFINE_GUID(0x49bd2028, 0x1523, 0x11d1, 0xad,0x79, 0x00,0xc0,0x4f,0xd8,0xfd,0xff)
CLSID_MofCompiler = DEFINE_GUID(0x6daf9757, 0x2e37, 0x11d2, 0xae,0xc9, 0x00,0xc0,0x4f,0xb6,0x88,0x20)
CLSID_WbemObjectTextSrc = DEFINE_GUID(0x8d1c559d, 0x84f0, 0x4bb3, 0xa7,0xd5, 0x56,0xa7,0x43,0x5a,0x9b,0xa6)
CLSID_WbemRefresher = DEFINE_GUID(0xc71566f2, 0x561e, 0x11d1, 0xad,0x87, 0x00,0xc0,0x4f,0xd8,0xfd,0xff)

class IDispatch(IUnknown): pass
class IRecordInfo(IUnknown): pass
class tagVARIANT(Structure): pass

class _VARIANT_NAME_4(Structure):
    _fields_ = [
        ('pvRecord', PVOID),
        ('pRecInfo', POINTER(IRecordInfo))
    ]

class _VARIANT_NAME_3(Union):
    _anonymous_ = ['__VARIANT_NAME_4']
    _fields_ = [
        ('llVal', LONGLONG),
        ('lVal', LONG),
        ('bVal', BYTE),
        ('iVal', SHORT),
        ('fltVal', FLOAT),
        ('dblVal', DOUBLE),
        ('boolVal', VARIANT_BOOL), 
        ('scode', SCODE),
        ('cyVal', CY),
        ('date', DATE),
        ('bstrVal', LPCWSTR),
        ('punkVal', POINTER(IUnknown)),
        ('pdispVal', POINTER(IDispatch)),
        ('parray', POINTER(SAFEARRAY)),
        ('pbVal', PBYTE),
        ('piVal', PSHORT),
        ('plVal', PLONG),
        ('pllVal', PLONGLONG),
        ('pfltVal', PFLOAT),
        ('pdblVal', PDOUBLE),
        ('pboolVal', POINTER(VARIANT_BOOL)),
        ('pscode', PSCODE),
        ('pcyVal', POINTER(CY)),
        ('pdate', POINTER(DATE)),
        ('pbstrVal', POINTER(BSTR)),
        ('ppunkVal', POINTER(POINTER(IUnknown))),
        ('ppdispVal', POINTER(POINTER(IDispatch))),
        ('pparray', POINTER(POINTER(SAFEARRAY))),
        ('pvarVal', POINTER(tagVARIANT)),
        ('byref', PVOID),
        ('cVal', CHAR),
        ('uiVal', USHORT),
        ('ulVal', ULONG),
        ('ullVal', ULONGLONG),
        ('intVal', INT),
        ('uintVal', UINT),
        ('pdecVal', POINTER(DECIMAL)),
        ('pcVal', PCHAR),
        ('puiVal', PUSHORT),
        ('pulVal', PULONG),
        ('pullVal', PULONGLONG),
        ('pintVal', PINT),
        ('puintVal', PUINT),
        ('__VARIANT_NAME_4', _VARIANT_NAME_4)
    ]

class _VARIANT_NAME_2(Structure):
    _anonymous_ = ['__VARIANT_NAME_3']
    _fields_ = [
        ('vt', VARTYPE),
        ('wReserved1', WORD),
        ('wReserved2', WORD),
        ('wReserved3', WORD),
        ('__VARIANT_NAME_3', _VARIANT_NAME_3)
    ]

class _VARIANT_NAME_1(Union):
    _anonymous_ = ['__VARIANT_NAME_2']
    _fields_ = [
        ('decVal', DECIMAL),
        ('__VARIANT_NAME_2', _VARIANT_NAME_2)
    ]

tagVARIANT._anonymous_ = ['__VARIANT_NAME_1']
tagVARIANT._fields_ = [('__VARIANT_NAME_1', _VARIANT_NAME_1)]

VARIANT = tagVARIANT
VARIANTARG = VARIANT

#############################################################

def IWbemQualifierSet_QueryInterface(This,riid,ppvObject): return IUnknown_QueryInterface(This,riid,ppvObject)
def IWbemQualifierSet_AddRef(This): return IUnknown_AddRef(This)
def IWbemQualifierSet_Release(This): return IUnknown_Release(This)


def IWbemQualifierSet_Get(This,wszName,lFlags,pVal,plFlavor) -> int:
    flags = [
        (_In_, 'wszName', LPCWSTR),
        (_In_, 'lFlags', LONG),
        (_In_, 'pVal', POINTER(VARIANT)),
        (_In_, 'plFlavor', POINTER(LONG))
    ]

    IWbemQualifierSet_Get = COMFUNCTYPE(
        3,
        'Get',
        argtypes=flags
    )

    res = IWbemQualifierSet_Get(This,wszName,lFlags,pVal,plFlavor)
    return res


def IWbemQualifierSet_Put(This,wszName,pVal,lFlavor) -> int:
    flags = [
        (_In_, 'wszName', LPCWSTR),
        (_In_, 'pVal', POINTER(VARIANT)),
        (_In_, 'lFlavor', LONG)
    ]

    IWbemQualifierSet_Put = COMFUNCTYPE(
        4,
        'Put',
        argtypes=flags
    )

    res = IWbemQualifierSet_Put(This,wszName,pVal,lFlavor)
    return res


def IWbemQualifierSet_Delete(This,wszName) -> int:
    IWbemQualifierSet_Delete = COMFUNCTYPE(
        5,
        'Delete',
        argtypes=[(_In_, 'wszName', LPCWSTR)]
    )

    res = IWbemQualifierSet_Delete(This, wszName)
    return res


def IWbemQualifierSet_GetNames(This,lFlags,pNames) -> int:
    IWbemQualifierSet_GetNames = COMFUNCTYPE(
        6,
        'GetNames',
        argtypes=[
            (_In_, 'lFlags', LONG),
            (_In_, 'pNames', SAFEARRAY)
        ]
    )
    
    res = IWbemQualifierSet_GetNames(This,lFlags,pNames)
    return res


def IWbemQualifierSet_BeginEnumeration(This,lFlags):
    IWbemQualifierSet_BeginEnumeration = COMFUNCTYPE(
        7,
        'BeginEnumeration',
        argtypes=[
            (_In_, 'lFlags', LONG)
        ]
    )

    res = IWbemQualifierSet_BeginEnumeration(This,lFlags)
    return res


def IWbemQualifierSet_Next(This,lFlags,pstrName,pVal,plFlavor) -> int:
    IWbemQualifierSet_Next = COMFUNCTYPE(
        8,
        'Next',
        argtypes=[
            (_In_, 'lFlags', LONG),
            (_In_, 'pstrName', BSTR),
            (_In_, 'pVal', VARIANT),
            (_In_, 'plFlavor', LONG)
        ]
    )

    res = IWbemQualifierSet_Next(This,lFlags,pstrName,pVal,plFlavor)
    return res


def IWbemQualifierSet_EndEnumeration(This) -> int:
    IWbemQualifierSet_EndEnumeration = COMFUNCTYPE(9, 'EndEnumeration')
    res = IWbemQualifierSet_EndEnumeration(This)
    return res


IID_IWbemQualifierSet = DEFINE_GUID(0xdc12a680, 0x737f, 0x11cf, 0x88,0x4d, 0x00,0xaa,0x00,0x4b,0x2e,0x24)
class IWbemQualifierSet(IUnknown):
    MIDL_INTERFACE = "dc12a680-737f-11cf-884d-00aa004b2e24"
    def Get(self,wszName,lFlags,pVal,plFlavor): return IWbemQualifierSet_Get(self.this,wszName,lFlags,pVal,plFlavor)
    def Put(self, wszName, pVal, lFlavor): return IWbemQualifierSet_Put(self.this, wszName, pVal, lFlavor)
    def Delete(self, wszName): return IWbemQualifierSet_Delete(self.this, wszName)
    def GetNames(self, lFlags, pNames): return IWbemQualifierSet_GetNames(self.this, lFlags, pNames)
    def BeginEnumeration(self, lFlags): return IWbemQualifierSet_BeginEnumeration(self.this, lFlags)
    def Next(self, lFlags, pstrName, pVal, plFlavor): return IWbemQualifierSet_Next(self.this, lFlags, pstrName, pVal, plFlavor)
    def EndEnumeration(self): return IWbemQualifierSet_EndEnumeration(self.this)


class IWbemQualifierSetVtbl(IWbemQualifierSet): pass


def IWbemClassObject_QueryInterface(This,riid,ppvObject): return IUnknown_QueryInterface(This,riid,ppvObject)
def IWbemClassObject_AddRef(This): return IUnknown_AddRef(This)
def IWbemClassObject_Release(This): return IUnknown_Release(This)


def IWbemClassObject_GetQualifierSet(This,ppQualSet) -> int:
    IWbemClassObject_GetQualifierSet = COMFUNCTYPE(
        3, 
        'GetQualifierSet',
        argtypes=[
            (_In_, 'ppQualSet', POINTER(POINTER(IWbemQualifierSet)))
        ]
    )

    res = IWbemClassObject_GetQualifierSet(This,ppQualSet)
    return res


def IWbemClassObject_Get(
    This,
    wszName,
    lFlags,
    pVal,
    pType,
    plFlavor
) -> int:
    
    IWbemClassObject_Get = COMFUNCTYPE(
        4,
        'Get',
        argtypes=[
            (_In_, 'wszName', LPCWSTR),
            (_In_, 'lFlags', LONG),
            (_In_, 'pVal', POINTER(VARIANT)),
            (_In_, 'pType', POINTER(CIMTYPE)),
            (_In_, 'plFlavor', POINTER(LONG))
        ]
    )

    res = IWbemClassObject_Get(
        This,
        wszName,
        lFlags,
        pVal,
        pType,
        plFlavor
    )

    return res


IWbemContext_Clone_Idx = 3
IWbemContext_GetNames_Idx = 4
IWbemContext_BeginEnumeration_Idx = 5
IWbemContext_Next_Idx = 6
IWbemContext_EndEnumeration_Idx = 7
IWbemContext_SetValue_Idx = 8
IWbemContext_GetValue_Idx = 9
IWbemContext_DeleteValue_Idx = 10
IWbemContext_DeleteAll_Idx = 11

IWbemClassObject_GetQualifierSet_Idx = 3
IWbemClassObject_Get_Idx = 4
IWbemClassObject_Put_Idx = 5
IWbemClassObject_Delete_Idx = 6
IWbemClassObject_GetNames_Idx = 7
IWbemClassObject_BeginEnumeration_Idx = 8
IWbemClassObject_Next_Idx = 9
IWbemClassObject_EndEnumeration_Idx = 10
IWbemClassObject_GetPropertyQualifierSet_Idx = 11
IWbemClassObject_Clone_Idx = 12
IWbemClassObject_GetObjectText_Idx = 13
IWbemClassObject_SpawnDerivedClass_Idx = 14
IWbemClassObject_SpawnInstance_Idx = 15
IWbemClassObject_CompareTo_Idx = 16
IWbemClassObject_GetPropertyOrigin_Idx = 17
IWbemClassObject_InheritsFrom_Idx = 18
IWbemClassObject_GetMethod_Idx = 19
IWbemClassObject_PutMethod_Idx = 20
IWbemClassObject_DeleteMethod_Idx = 21
IWbemClassObject_BeginMethodEnumeration_Idx = 22
IWbemClassObject_NextMethod_Idx = 23
IWbemClassObject_EndMethodEnumeration_Idx = 24
IWbemClassObject_GetMethodQualifierSet_Idx = 25
IWbemClassObject_GetMethodOrigin_Idx = 26

IWbemLocator_ConnectServer_Idx = 3

IEnumWbemClassObject_Reset_Idx = 3
IEnumWbemClassObject_Next_Idx = 4
IEnumWbemClassObject_NextAsync_Idx = 5
IEnumWbemClassObject_Clone_Idx = 6
IEnumWbemClassObject_Skip_Idx = 7

IWbemServices_OpenNamespace_Idx = 3
IWbemServices_CancelAsyncCall_Idx = 4
IWbemServices_QueryObjectSink_Idx = 5
IWbemServices_GetObject_Idx = 6
IWbemServices_GetObjectAsync_Idx = 7
IWbemServices_PutClass_Idx = 8
IWbemServices_PutClassAsync_Idx = 9
IWbemServices_DeleteClass_Idx = 10
IWbemServices_DeleteClassAsync_Idx = 11
IWbemServices_CreateClassEnum_Idx = 12
IWbemServices_CreateClassEnumAsync_Idx = 13
IWbemServices_PutInstance_Idx = 14
IWbemServices_PutInstanceAsync_Idx = 15
IWbemServices_DeleteInstance_Idx = 16
IWbemServices_DeleteInstanceAsync_Idx = 17
IWbemServices_CreateInstanceEnum_Idx = 18
IWbemServices_CreateInstanceEnumAsync_Idx = 19
IWbemServices_ExecQuery_Idx = 20
IWbemServices_ExecQueryAsync_Idx = 21
IWbemServices_ExecNotificationQuery_Idx = 22
IWbemServices_ExecNotificationQueryAsync_Idx = 23
IWbemServices_ExecMethod_Idx = 24
IWbemServices_ExecMethodAsync_Idx = 25

class IWbemClassObject(IUnknown):
    def BeginEnumeration(self, lEnumFlags):
        flags = ((_In_, 'lEnumFlags'))
        BeginEnumeration = CALLBACK(HRESULT, LONG)
        BeginEnumeration = BeginEnumeration(
            IWbemClassObject_BeginEnumeration_Idx,
            'lEnumFlags',
            flags
        )
        res = lEnumFlags(self.this, lEnumFlags)
        return res
    

    def BeginMethodEnumeration(self, lEnumFlags):
        flags = ((_In_, 'lEnumFlags'))
        BeginMethodEnumeration = CALLBACK(HRESULT, LONG)
        BeginMethodEnumeration = BeginMethodEnumeration(
            IWbemClassObject_BeginMethodEnumeration_Idx,
            'BeginMethodEnumeration',
            flags
        )
        res = BeginMethodEnumeration(self.this, lEnumFlags)
        return res
    

    def Clone(self, ppCopy):
        flags = ((_In_, 'ppCopy'))
        Clone = CALLBACK(HRESULT, IWbemClassObject)
        Clone = Clone(IWbemClassObject_Clone_Idx,
                      'Clone',
                      flags
        )
        res = Clone(self.this, ppCopy)
        return res
    

    def CompareTo(self, lFlags, pCompareTo):
        flags = ((_In_, 'lFlags'), 
                 (_In_, 'pCompareTo')
        )
        CompareTo = CALLBACK(HRESULT, LONG, IWbemClassObject)
        CompareTo = CompareTo(IWbemClassObject_CompareTo_Idx,
                              'CompareTo',
                              flags
        )
        res = CompareTo(self.this, lFlags, pCompareTo)
        return res
    
    def Get(
        self,
        wszName,
        lFlags,
        pVal,
        pType,
        plFlavor
    ):
        
        flags = (
            (_In_, 'wszName'),
            (_In_, 'lFlags'),
            (_In_, 'pVal'),
            (_In_, 'pType'),
            (_In_, 'plFlavor')
        )

        Get = CALLBACK(
            HRESULT,
            LPCWSTR,
            LONG,
            POINTER(VARIANT),
            CIMTYPE,
            LONG
        )

        Get = Get(
            IWbemClassObject_Get_Idx,
            'Get',
            flags
        )

        res = Get(
            self.this,
            wszName,
            lFlags,
            pVal,
            pType,
            plFlavor
        )

        return res


class IWbemContext(IUnknown):
    def Clone(self, ppNewCopy):
        flags = (_In_, 'ppNewCopy')
        Clone = CALLBACK(HRESULT, VOID)
        Clone = Clone(
            IWbemContext_Clone_Idx,
            'Clone',
            flags
        )

        res = Clone(self.this, ppNewCopy)
        return res

    def GetNames(self, lFlags, pNames):
        flags = ((_In_, 'lFlags'),
                 (_In_, 'pNames')
        )

        GetNames = CALLBACK(HRESULT, LONG, SAFEARRAY)
        GetNames = GetNames(
            IWbemContext_GetNames_Idx,
            'GetNames',
            flags
        )
        res = GetNames(self.this, lFlags, pNames)
        return res
    

    def BeginEnumeration(self, lFlags):
        flags = ((_In_, 'lFlags'))
        BeginEnumeration = CALLBACK(HRESULT, LONG)
        BeginEnumeration = BeginEnumeration(
            IWbemContext_BeginEnumeration_Idx,
            'BeginEnumeration',
            flags
        )

        res = BeginEnumeration(self.this, lFlags)
        return res


    def Next(self, lFlags, pstrName, pValue):
        flags = ((_In_, 'lFlags'),
                 (_In_, 'pstrName'),
                 (_In_, 'pValue')
        )

        Next = CALLBACK(HRESULT, LONG, BSTR, VARIANT)
        Next = Next(
            IWbemContext_Next_Idx,
            'Next',
            flags
        )

        res = Next(self.this, lFlags, pstrName, pValue)
        return res
    

    def EndEnumeration(self):
        flags = ()
        EndEnumeration = CALLBACK(HRESULT)
        EndEnumeration = EndEnumeration(
            IWbemContext_EndEnumeration_Idx,
            'EndEnumeration',
            flags
        )

        res = EndEnumeration(self.this)
        return res


    def GetValue(self, wszName, lFlags, pValue):
        flags = ((_In_, 'wszName'),
                 (_In_, 'lFlags'),
                 (_In_, 'pValue')
        )
        GetValue = CALLBACK(HRESULT, LPCWSTR, LONG, VARIANT)
        GetValue = GetValue(
            IWbemContext_GetValue_Idx,
            'GetValue',
            flags
        )
        
        res = GetValue(self.this, wszName, lFlags, pValue)
        return res


    def SetValue(self, wszName, lFlags, pValue):
        flags = ((_In_, 'wszName'),
                 (_In_, 'lFlags'),
                 (_In_, 'pValue')
        )
        SetValue = CALLBACK(HRESULT, LPCWSTR, LONG, VARIANT)
        SetValue = SetValue(IWbemContext_GetValue_Idx,
                            'GetValue',
                            flags
        )
        
        res = SetValue(self.this, wszName, lFlags, pValue)
        return res
    

    def DeleteValue(self, wszName, lFlags):
        flags = ((_In_, 'wszName'), 
                 (_In_, 'lFlags')
        )

        DeleteValue = CALLBACK(HRESULT, LPCWSTR, LONG)
        DeleteValue = DeleteValue(
            IWbemContext_DeleteValue_Idx,
            'DeleteValue',
            flags
        )
        res = DeleteValue(self.this, wszName, lFlags)
        return res
        

    def DeleteAll(self):
        flags = ()
        DeleteAll = CALLBACK(HRESULT)
        DeleteAll = DeleteAll(
            IWbemContext_DeleteAll_Idx,
            'DeleteAll',
            flags
        )
        res = DeleteAll(self.this)
        return res
    


    # ......

class IEnumWbemClassObject(IUnknown):
    def Reset(self):
        flags = ()
        Reset = CALLBACK(HRESULT)
        Reset = Reset(
            IEnumWbemClassObject_Reset_Idx,
            'Reset',
            flags
        )

        res = Reset(self.this)
        return res
    
    def Next(
        self,
        lTimeout: int,
        uCount: int,
        apObjects: Any,
        puReturned: Any
    ):
        
        flags = (
            (_In_, 'lTimeout'),
            (_In_, 'uCount'),
            (_In_, 'apObjects'),
            (_In_, 'puReturned')
        )
        Next = CALLBACK(
            HRESULT,
            LONG,
            ULONG,
            POINTER(IWbemClassObject),
            POINTER(ULONG)
        )

        Next = Next(
            IEnumWbemClassObject_Next_Idx,
            'Next',
            flags
        )

        res = Next(
            self.this,
            lTimeout,
            uCount,
            apObjects,
            puReturned
        )

        return res

class IWbemObjectSink(IUnknown):
    def Indicate(self, lObjectCount, apObjArray):
        Indicate = CALLBACK(HRESULT, LONG, )


class IWbemServices(IUnknown):
    def CancelAsyncCall(self, pSink):
        flags = ((_In_, 'pSink'))
        CancelAsyncCall = CALLBACK(HRESULT, POINTER(IWbemObjectSink))
        CancelAsyncCall = CancelAsyncCall(

        )

    def ExecQuery(
        self, 
        strQueryLanguage: str, 
        strQuery: str,
        lFlags: int,
        pCtx: Any,
        ppEnum: Any
    ):
        
        flags = (
            (_In_, 'strQueryLanguage'),
            (_In_, 'strQuery'),
            (_In_, 'lFlags'),
            (_In_, 'pCtx'),
            (_In_, 'ppEnum')
        )

        ExecQuery = CALLBACK(
            HRESULT,
            BSTR,
            BSTR,
            LONG,
            IWbemContext,
            POINTER(IEnumWbemClassObject)
        )

        ExecQuery = ExecQuery(
            IWbemServices_ExecQuery_Idx,
            'ExecQuery',
            flags
        )
        
        res = ExecQuery(
            self.this,
            strQueryLanguage,
            strQuery,
            lFlags,
            pCtx,
            ppEnum
        )

        return res
        
        
class IWbemLocator(IUnknown):
    def ConnectServer(
        self,
        strNetworkResource: str,
        strUser: str,
        strPassword: str,
        strLocale: str,
        lSecurityFlags: Any,
        strAuthority: str,
        pCtx: Any,
        ppNamespace
    ) -> int:

        flags = [
            (_In_, 'strNetworkResource', BSTR, ),
            (_In_, 'strUser', BSTR),
            (_In_, 'strPassword', BSTR),
            (_In_, 'strLocale', BSTR),
            (_In_, 'lSecurityFlags', LONG),
            (_In_, 'strAuthority', BSTR),
            (_In_, 'pCtx', POINTER(IWbemContext)),
            (_In_, 'ppNamespace', POINTER(IWbemServices))
        ]

        ConnectServer = COMFUNCTYPE(
            IWbemLocator_ConnectServer_Idx,
            'ConnectServer',
            HRESULT,
            flags
        )

        res = ConnectServer(
            self.this,
            strNetworkResource,
            strUser,
            strPassword,
            strLocale,
            lSecurityFlags,
            strAuthority,
            pCtx,
            ppNamespace
        )

        return res
    