# coding = 'utf-8'

from method.System.windef import *
from method.System.sdkddkver import *
from method.System.winusutypes import *

WINBOOL = BOOL
_WIN32_WINNT = WIN32_WINNT
__LONG32 = LONG if sys.maxsize > 2**32 else INT

# wingdi.h

R2_BLACK = 1
R2_NOTMERGEPEN = 2
R2_MASKNOTPEN = 3
R2_NOTCOPYPEN = 4
R2_MASKPENNOT = 5
R2_NOT = 6
R2_XORPEN = 7
R2_NOTMASKPEN = 8
R2_MASKPEN = 9
R2_NOTXORPEN = 10
R2_NOP = 11
R2_MERGENOTPEN = 12
R2_COPYPEN = 13
R2_MERGEPENNOT = 14
R2_MERGEPEN = 15
R2_WHITE = 16
R2_LAST = 16

SRCCOPY = DWORD(0x00CC0020).value
SRCPAINT = DWORD(0x00EE0086).value
SRCAND = DWORD(0x008800C6).value
SRCINVERT = DWORD(0x00660046).value
SRCERASE = DWORD(0x00440328).value
NOTSRCCOPY = DWORD(0x00330008).value
NOTSRCERASE = DWORD(0x001100A6).value
MERGECOPY = DWORD(0x00C000CA).value
MERGEPAINT = DWORD(0x00BB0226).value
PATCOPY = DWORD(0x00F00021).value
PATPAINT = DWORD(0x00FB0A09).value
PATINVERT = DWORD(0x005A0049).value
DSTINVERT = DWORD(0x00550009).value
BLACKNESS = DWORD(0x00000042).value
WHITENESS = DWORD(0x00FF0062).value
NOMIRRORBITMAP = DWORD(0x80000000).value
CAPTUREBLT = DWORD(0x40000000).value


def MAKEROP4(fore,back):
    return DWORD(((back << 8) & 0xFF000000) | fore).value


GDI_ERROR = 0xFFFFFFFF
HGDI_ERROR = 0xFFFFFFFF

ERROR = 0
NULLREGION = 1
SIMPLEREGION = 2
COMPLEXREGION = 3
RGN_ERROR = ERROR

RGN_AND = 1
RGN_OR = 2
RGN_XOR = 3
RGN_DIFF = 4
RGN_COPY = 5
RGN_MIN = RGN_AND
RGN_MAX = RGN_COPY

BLACKONWHITE = 1
WHITEONBLACK = 2
COLORONCOLOR = 3
HALFTONE = 4
MAXSTRETCHBLTMODE = 4

STRETCH_ANDSCANS = BLACKONWHITE
STRETCH_ORSCANS = WHITEONBLACK
STRETCH_DELETESCANS = COLORONCOLOR
STRETCH_HALFTONE = HALFTONE

ALTERNATE = 1
WINDING = 2
POLYFILL_LAST = 2

LAYOUT_RTL = 0x00000001
LAYOUT_BTT = 0x00000002
LAYOUT_VBH = 0x00000004
LAYOUT_ORIENTATIONMASK = (LAYOUT_RTL | LAYOUT_BTT | LAYOUT_VBH)
LAYOUT_BITMAPORIENTATIONPRESERVED = 0x00000008

TA_NOUPDATECP = 0
TA_UPDATECP = 1

TA_LEFT = 0
TA_RIGHT = 2
TA_CENTER = 6

TA_TOP = 0
TA_BOTTOM = 8
TA_BASELINE = 24
TA_RTLREADING = 256
TA_MASK = (TA_BASELINE+TA_CENTER+TA_UPDATECP+TA_RTLREADING)

VTA_BASELINE = TA_BASELINE
VTA_LEFT = TA_BOTTOM
VTA_RIGHT = TA_TOP
VTA_CENTER = TA_CENTER
VTA_BOTTOM = TA_RIGHT
VTA_TOP = TA_LEFT

ETO_OPAQUE = 0x0002
ETO_CLIPPED = 0x0004
ETO_GLYPH_INDEX = 0x0010
ETO_RTLREADING = 0x0080
ETO_NUMERICSLOCAL = 0x0400
ETO_NUMERICSLATIN = 0x0800
ETO_IGNORELANGUAGE = 0x1000
ETO_PDY = 0x2000
#if _WIN32_WINNT >= 0x0600
ETO_REVERSE_INDEX_MAP = 0x10000
#endif

ASPECT_FILTERING = 0x0001

DCB_RESET = 0x0001
DCB_ACCUMULATE = 0x0002
DCB_DIRTY = DCB_ACCUMULATE
DCB_SET = (DCB_RESET | DCB_ACCUMULATE)
DCB_ENABLE = 0x0004
DCB_DISABLE = 0x0008

#ifndef NOMETAFILE

META_SETBKCOLOR = 0x0201
META_SETBKMODE = 0x0102
META_SETMAPMODE = 0x0103
META_SETROP2 = 0x0104
META_SETRELABS = 0x0105
META_SETPOLYFILLMODE = 0x0106
META_SETSTRETCHBLTMODE = 0x0107
META_SETTEXTCHAREXTRA = 0x0108
META_SETTEXTCOLOR = 0x0209
META_SETTEXTJUSTIFICATION = 0x020A
META_SETWINDOWORG = 0x020B
META_SETWINDOWEXT = 0x020C
META_SETVIEWPORTORG = 0x020D
META_SETVIEWPORTEXT = 0x020E
META_OFFSETWINDOWORG = 0x020F
META_SCALEWINDOWEXT = 0x0410
META_OFFSETVIEWPORTORG = 0x0211
META_SCALEVIEWPORTEXT = 0x0412
META_LINETO = 0x0213
META_MOVETO = 0x0214
META_EXCLUDECLIPRECT = 0x0415
META_INTERSECTCLIPRECT = 0x0416
META_ARC = 0x0817
META_ELLIPSE = 0x0418
META_FLOODFILL = 0x0419
META_PIE = 0x081A
META_RECTANGLE = 0x041B
META_ROUNDRECT = 0x061C
META_PATBLT = 0x061D
META_SAVEDC = 0x001E
META_SETPIXEL = 0x041F
META_OFFSETCLIPRGN = 0x0220
META_TEXTOUT = 0x0521
META_BITBLT = 0x0922
META_STRETCHBLT = 0x0B23
META_POLYGON = 0x0324
META_POLYLINE = 0x0325
META_ESCAPE = 0x0626
META_RESTOREDC = 0x0127
META_FILLREGION = 0x0228
META_FRAMEREGION = 0x0429
META_INVERTREGION = 0x012A
META_PAINTREGION = 0x012B
META_SELECTCLIPREGION = 0x012C
META_SELECTOBJECT = 0x012D
META_SETTEXTALIGN = 0x012E
META_CHORD = 0x0830
META_SETMAPPERFLAGS = 0x0231
META_EXTTEXTOUT = 0x0a32
META_SETDIBTODEV = 0x0d33
META_SELECTPALETTE = 0x0234
META_REALIZEPALETTE = 0x0035
META_ANIMATEPALETTE = 0x0436
META_SETPALENTRIES = 0x0037
META_POLYPOLYGON = 0x0538
META_RESIZEPALETTE = 0x0139
META_DIBBITBLT = 0x0940
META_DIBSTRETCHBLT = 0x0b41
META_DIBCREATEPATTERNBRUSH = 0x0142
META_STRETCHDIB = 0x0f43
META_EXTFLOODFILL = 0x0548
META_SETLAYOUT = 0x0149
META_DELETEOBJECT = 0x01f0
META_CREATEPALETTE = 0x00f7
META_CREATEPATTERNBRUSH = 0x01F9
META_CREATEPENINDIRECT = 0x02FA
META_CREATEFONTINDIRECT = 0x02FB
META_CREATEBRUSHINDIRECT = 0x02FC
META_CREATEREGION = 0x06FF

class _DRAWPATRECT(Structure):
    _fields_ = [('ptPosition', POINT),
                ('ptSize', POINT),
                ('wStyle', WORD),
                ('wPattern', WORD),
    ]

DRAWPATRECT = _DRAWPATRECT
PDRAWPATRECT = POINTER(DRAWPATRECT)

NEWFRAME = 1
ABORTDOC = 2
NEXTBAND = 3
SETCOLORTABLE = 4
GETCOLORTABLE = 5
FLUSHOUTPUT = 6
DRAFTMODE = 7
QUERYESCSUPPORT = 8
SETABORTPROC = 9
STARTDOC = 10
ENDDOC = 11
GETPHYSPAGESIZE = 12
GETPRINTINGOFFSET = 13
GETSCALINGFACTOR = 14
MFCOMMENT = 15
GETPENWIDTH = 16
SETCOPYCOUNT = 17
SELECTPAPERSOURCE = 18
DEVICEDATA = 19
PASSTHROUGH = 19
GETTECHNOLGY = 20
GETTECHNOLOGY = 20
SETLINECAP = 21
SETLINEJOIN = 22
SETMITERLIMIT = 23
BANDINFO = 24
DRAWPATTERNRECT = 25
GETVECTORPENSIZE = 26
GETVECTORBRUSHSIZE = 27
ENABLEDUPLEX = 28
GETSETPAPERBINS = 29
GETSETPRINTORIENT = 30
ENUMPAPERBINS = 31
SETDIBSCALING = 32
EPSPRINTING = 33
ENUMPAPERMETRICS = 34
GETSETPAPERMETRICS = 35
POSTSCRIPT_DATA = 37
POSTSCRIPT_IGNORE = 38
MOUSETRAILS = 39
GETDEVICEUNITS = 42

GETEXTENDEDTEXTMETRICS = 256
GETEXTENTTABLE = 257
GETPAIRKERNTABLE = 258
GETTRACKKERNTABLE = 259
EXTTEXTOUT = 512
GETFACENAME = 513
DOWNLOADFACE = 514
ENABLERELATIVEWIDTHS = 768
ENABLEPAIRKERNING = 769
SETKERNTRACK = 770
SETALLJUSTVALUES = 771
SETCHARSET = 772

STRETCHBLT = 2048
METAFILE_DRIVER = 2049
GETSETSCREENPARAMS = 3072
QUERYDIBSUPPORT = 3073
BEGIN_PATH = 4096
CLIP_TO_PATH = 4097
END_PATH = 4098
EXT_DEVICE_CAPS = 4099
RESTORE_CTM = 4100
SAVE_CTM = 4101
SET_ARC_DIRECTION = 4102
SET_BACKGROUND_COLOR = 4103
SET_POLY_MODE = 4104
SET_SCREEN_ANGLE = 4105
SET_SPREAD = 4106
TRANSFORM_CTM = 4107
SET_CLIP_BOX = 4108
SET_BOUNDS = 4109
SET_MIRROR_MODE = 4110
OPENCHANNEL = 4110
DOWNLOADHEADER = 4111
CLOSECHANNEL = 4112
POSTSCRIPT_PASSTHROUGH = 4115
ENCAPSULATED_POSTSCRIPT = 4116

POSTSCRIPT_IDENTIFY = 4117
POSTSCRIPT_INJECTION = 4118

CHECKJPEGFORMAT = 4119
CHECKPNGFORMAT = 4120

GET_PS_FEATURESETTING = 4121
GDIPLUS_TS_QUERYVER = 4122
GDIPLUS_TS_RECORD = 4123

if _WIN32_WINNT >= 0x0600:
    MILCORE_TS_QUERYVER_RESULT_FALSE = 0x0
    MILCORE_TS_QUERYVER_RESULT_TRUE =  0x7FFFFFFF


SPCLPASSTHROUGH2 = 4568

PSIDENT_GDICENTRIC = 0
PSIDENT_PSCENTRIC = 1

class _PSINJECTDATA(Structure):
    _fields_ = [('DataBytes', DWORD),
                ('InjectionPoint', WORD),
                ('PageNumber', WORD),
    ]

PSINJECTDATA = _PSINJECTDATA
PPSINJECTDATA = POINTER(PSINJECTDATA)

PSINJECT_BEGINSTREAM = 1
PSINJECT_PSADOBE = 2
PSINJECT_PAGESATEND = 3
PSINJECT_PAGES = 4

PSINJECT_DOCNEEDEDRES = 5
PSINJECT_DOCSUPPLIEDRES = 6
PSINJECT_PAGEORDER = 7
PSINJECT_ORIENTATION = 8
PSINJECT_BOUNDINGBOX = 9
PSINJECT_DOCUMENTPROCESSCOLORS = 10

PSINJECT_COMMENTS = 11
PSINJECT_BEGINDEFAULTS = 12
PSINJECT_ENDDEFAULTS = 13
PSINJECT_BEGINPROLOG = 14
PSINJECT_ENDPROLOG = 15
PSINJECT_BEGINSETUP = 16
PSINJECT_ENDSETUP = 17
PSINJECT_TRAILER = 18
PSINJECT_EOF = 19
PSINJECT_ENDSTREAM = 20
PSINJECT_DOCUMENTPROCESSCOLORSATEND = 21

PSINJECT_PAGENUMBER = 100
PSINJECT_BEGINPAGESETUP = 101
PSINJECT_ENDPAGESETUP = 102
PSINJECT_PAGETRAILER = 103
PSINJECT_PLATECOLOR = 104

PSINJECT_SHOWPAGE = 105
PSINJECT_PAGEBBOX = 106
PSINJECT_ENDPAGECOMMENTS = 107

PSINJECT_VMSAVE = 200
PSINJECT_VMRESTORE = 201

PSINJECT_DLFONT = 0xdddddddd

FEATURESETTING_NUP = 0
FEATURESETTING_OUTPUT = 1
FEATURESETTING_PSLEVEL = 2
FEATURESETTING_CUSTPAPER = 3
FEATURESETTING_MIRROR = 4
FEATURESETTING_NEGATIVE = 5
FEATURESETTING_PROTOCOL = 6

FEATURESETTING_PRIVATE_BEGIN = 0x1000
FEATURESETTING_PRIVATE_END = 0x1FFF

class _PSFEATURE_OUTPUT(Structure):
    _fields_ = [('bPageIndependent', WINBOOL),
                ('bSetPageDevice', WINBOOL)
    ]

PSFEATURE_OUTPUT = _PSFEATURE_OUTPUT
PPSFEATURE_OUTPUT = POINTER(PSFEATURE_OUTPUT)

class _PSFEATURE_CUSTPAPER(Structure):
    _fields_ = [('lOrientation', LONG),
                ('lWidth', LONG),
                ('lHeight', LONG),
                ('lWidthOffset', LONG),
                ('lHeightOffset', LONG),
    ]

PSFEATURE_CUSTPAPER = _PSFEATURE_CUSTPAPER
PPSFEATURE_CUSTPAPER = POINTER(PSFEATURE_CUSTPAPER)

PSPROTOCOL_ASCII = 0
PSPROTOCOL_BCP = 1
PSPROTOCOL_TBCP = 2
PSPROTOCOL_BINARY = 3

QDI_SETDIBITS = 1
QDI_GETDIBITS = 2
QDI_DIBTOSCREEN = 4
QDI_STRETCHDIB = 8

SP_NOTREPORTED = 0x4000
SP_ERROR = -1
SP_APPABORT = -2
SP_USERABORT = -3
SP_OUTOFDISK = -4
SP_OUTOFMEMORY = -5

PR_JOBSTATUS = 0x0000

OBJ_PEN = 1
OBJ_BRUSH = 2
OBJ_DC = 3
OBJ_METADC = 4
OBJ_PAL = 5
OBJ_FONT = 6
OBJ_BITMAP = 7
OBJ_REGION = 8
OBJ_METAFILE = 9
OBJ_MEMDC = 10
OBJ_EXTPEN = 11
OBJ_ENHMETADC = 12
OBJ_ENHMETAFILE = 13
OBJ_COLORSPACE = 14

GDI_OBJ_LAST = OBJ_COLORSPACE

MWT_IDENTITY = 1
MWT_LEFTMULTIPLY = 2
MWT_RIGHTMULTIPLY = 3

MWT_MIN = MWT_IDENTITY
MWT_MAX = MWT_RIGHTMULTIPLY

class tagXFORM(Structure):
    _fields_ = [('eM11', FLOAT),
                ('eM12', FLOAT),
                ('eM21', FLOAT),
                ('eM22', FLOAT),
                ('eDx', FLOAT),
                ('eDy', FLOAT),
    ]

XFORM = tagXFORM
PXFORM = POINTER(XFORM)
LPXFORM = PXFORM

class tagBITMAP(Structure):
    _fields_ = [('bmType', LONG),
                ('bmWidth', LONG),
                ('bmHeight', LONG),
                ('bmWidthBytes', LONG),
                ('bmPlanes', WORD),
                ('bmBitsPixel', WORD),
                ('bmBits', LPVOID),
    ]

BITMAP = tagBITMAP
PBITMAP = POINTER(BITMAP)
NPBITMAP = PBITMAP
LPBITMAP = PBITMAP

class tagRGBTRIPLE(Structure):
    _fields_ = [('rgbtBlue', BYTE),
                ('rgbtGreen', BYTE),
                ('rgbtRed', BYTE),
    ]

RGBTRIPLE = tagRGBTRIPLE
PRGBTRIPLE = POINTER(RGBTRIPLE)
NPRGBTRIPLE = PRGBTRIPLE
LPRGBTRIPLE = PRGBTRIPLE

class tagRGBQUAD(Structure):
    _fields_ = [('rgbBlue', BYTE),
                ('rgbGreen', BYTE),
                ('rgbRed', BYTE),
                ('rgbReserved', BYTE),
    ]

RGBQUAD = tagRGBQUAD
LPRGBQUAD = POINTER(RGBQUAD)

CS_ENABLE = 0x00000001
CS_DISABLE = 0x00000002
CS_DELETE_TRANSFORM = 0x00000003

LCS_SIGNATURE = 'PSOC'

LCS_sRGB = 'sRGB'
LCS_WINDOWS_COLOR_SPACE = 'Win '

LCSCSTYPE = LONG

LCS_CALIBRATED_RGB = 0x00000000

LCSGAMUTMATCH = LONG

LCS_GM_BUSINESS = 0x00000001
LCS_GM_GRAPHICS = 0x00000002
LCS_GM_IMAGES = 0x00000004
LCS_GM_ABS_COLORIMETRIC = 0x00000008

CM_OUT_OF_GAMUT = 255
CM_IN_GAMUT = 0

ICM_ADDPROFILE = 1
ICM_DELETEPROFILE = 2
ICM_QUERYPROFILE = 3
ICM_SETDEFAULTPROFILE = 4
ICM_REGISTERICMATCHER = 5
ICM_UNREGISTERICMATCHER = 6
ICM_QUERYMATCH = 7


def GetKValue(cmyk):
    return BYTE(cmyk).value


def GetYValue(cmyk):
    return BYTE(cmyk >> 8).value


def GetMValue(cmyk):
    return BYTE(cmyk >> 16).value


def GetCValue(cmyk):
    return BYTE(cmyk >> 24).value


def CMYK(c: int, m: int, y: int, k: int) -> int:
    a1 = BYTE(k).value | WORD(BYTE(y).value).value << 8
    a2 = DWORD(BYTE(m).value).value << 16
    a3 = DWORD(BYTE(c).value).value << 24
    return COLORREF((a1 | a2) | a3).value


FXPT16DOT16 = __LONG32
LPFXPT16DOT16 = POINTER(FXPT16DOT16)

FXPT2DOT30 = __LONG32
LPFXPT2DOT30 = POINTER(FXPT2DOT30)

class tagCIEXYZ(Structure):
    _fields_ = [('ciexyzX', FXPT2DOT30),
                ('ciexyzY', FXPT2DOT30),
                ('ciexyzZ', FXPT2DOT30),
    ]

CIEXYZ = tagCIEXYZ
LPCIEXYZ = POINTER(CIEXYZ)

class tagICEXYZTRIPLE(Structure):
    _fields_ = [('ciexyzRed', CIEXYZ),
                ('ciexyzGreen', CIEXYZ),
                ('ciexyzBlue', CIEXYZ),
    ]

CIEXYZTRIPLE = tagICEXYZTRIPLE
LPCIEXYZTRIPLE = POINTER(CIEXYZTRIPLE)


LF_FACESIZE         = 32